columns:
  - TRANSACTION_ID
  - CUSTOMER_ID
  - TERMINAL_ID
  - TX_AMOUNT
  - TX_TIME_SECONDS
  - TX_TIME_DAYS
  - TX_FRAUD
  - TX_FRAUD_SCENARIO
  - Year
  - Month
  - Day
  - Hour
  - Minutes
  - Seconds





numerical_columns:
  - TRANSACTION_ID
  - CUSTOMER_ID
  - TERMINAL_ID
  - TX_AMOUNT
  - TX_TIME_SECONDS
  - TX_TIME_DAYS
  - TX_FRAUD
  - TX_FRAUD_SCENARIO
  - Year
  - Month
  - Day
  - Hour
  - Minutes
  - Seconds
